### PR TITLE
add manpage and Makefile

### PR DESCRIPTION
**Pull request by Leon-Plickat**
I created a manpage based on your README.

I do not know how to make cargo install it, so I left that out for now.

## Pull request checklist

- [X] The tests are passing locally as well as on CI -> `man` displays it correclty
- [ ] ~~The changelog was updated (in `CHANGELOG.md`)~~ not a feature, so does not apply
- [ ] ~~If commands were added/modified, the documentation was adapted~~

### CODE REVIEW

**Comment by beatbrot** [comment]
Thank you very much for your contribution! 

First of all: The manpage itself looks great!

But what I worry more about is, how we can create a nice install workflow. As discussed [here](https://github.com/rust-lang/cargo/issues/2729), `cargo install` does not support installing manpages. 

This effectively means we need an alternative way of installing trackie. I think we have a few possibilities here:

1. Distribute trackie as a `.deb` package. Afaik Ubuntu/Debian are widely used distros and I am sure `.deb` packages are able to bundle man-pages. I have to admit though, that I have no idea on how to create such a package. But I guess it can't be too hard
2. Provide a `trackie install` command so that trackie can install itself. It could then also copy the manpage in the correct directory and I guess we would be fine then? This would probably be a linux-only command as Windows doesn't really have a nice location to put binaries into.

What is your opinion on that? What is the better alternative? Do you have another solution in mind?

**Comment by Leon-Plickat** [comment]
I personally think the best option is to wrap cargo in `make`. A simple Makefile is simple to create (I can add one if you like) and can install all files in an idiomatic way that makes it straight-forward for package maintainers to package trackie for their repositories.

I advise against creating a `.deb` package, that really is the job of the packagers, not the project developers, and it would add an unnecessary hurdle for packaging trackie into other distributions repositories.

**Comment by beatbrot** [comment]
Just to be sure: Even if we would add such a Makefile, windows uses still would be able to directly use cargo, right?

**Comment by Leon-Plickat** [comment]
Adding a Makefile would leave everything as it is right now, it simply adds an additional way to initiate the build and install the files.

**Comment by beatbrot** [comment]
Sounds great! Thanks so much for all your help on this!

**Comment by beatbrot** [comment]
So if you could add a `Makefile` to this PR and maybe update the README, we can merge your PR into master :)

**Comment by Leon-Plickat** [comment]
Makefile has been added

**Comment by beatbrot** [comment]
Works like a charm! Thank you so much! Will merge this as soon as the checks are done.

**Pull request merged**
